<GameField>:

    viewclass: 'Cell'

    RecycleGridLayout:
        cols: 20
        rows: 10
        default_size: 100, 100
        default_size_hint: None, None
        size_hint_y: None
        size_hint_x: None
        size: self.minimum_size

<CorporationGame>:
    game_field: field

    orientation: 'vertical'
    BoxLayout:
        size_hint: 1, 0.1
    FloatLayout:
        GameField:
            id: field
            size_hint: 1.2, 1.2
            pos_hint: {'center': (.5, .5)}
